---
- name: Install git
  action: apt pkg=git-core state=installed
#  become: yes
#  become_method: sudo
#  become_user: root
- name: Create git group
  group: name=git
  become: yes
  become_method: sudo
  become_user: root
- name: Create git user
  user: name=git groups=git,{{http_user}} append=yes shell=/bin/bash home=/home/git
  become: yes
  become_method: sudo
  become_user: root
- name: Set up GitHub deployment key
  become: yes
  become_method: sudo
  become_user: git
  command: cp /tmp/docs_deploy_key /home/git/.ssh/id_rsa
- name: Change GitHub deployment key permissions
  become: yes
  become_method: sudo
  become_user: git
  command: chmod 600 /home/git/.ssh/id_rsa
- name: Setup git repo with git user authorized_key
  become: yes
  become_method: sudo
  become_user: git
  git: repo={{git_repo}}
       version={{git_branch}}
       dest=/home/git/{{git_repo_dir}}/{{git_repo}}
       accept_hostkey=True
- name: Initialize bare git repo
  command: git init --bare chdir=/home/git/{{git_repo_dir}}/{{git_repo}}
  become: yes
  become_method: sudo
  become_user: git
- name: Copy post-receive hook
  template: src=post-receive dest=/home/git/{{git_repo_dir}}/{{git_repo}}/hooks/post-receive
  become: yes
  become_method: sudo
  become_user: root
  args:
    owner: git
    group: users
    mode: 0755