---
- name: Install git
  action: apt pkg=git-core state=installed
- name: read-write git checkout from repo
  become_user: "{{ git_user }}"
  git:
    repo: "{{ git_repo_url }}"
    dest: "/home/{{ git_user }}/{{ git_repo }}"
    version: "{{ git_branch }}"
- name: Copy post-receive hook
  template: src=post-receive dest=/home/cloud-user/summit-example/.git/hooks/post-receive
  become: yes
  become_method: sudo
  args:
    owner: "{{ git_user }}"
    group: git
    mode: 0755
