---
- name: Install git
  action: apt pkg=git-core state=installed
- name: Create git group
  group: name=git
- name: Create git user
  user: name=git groups=git,{{http_user}} append=yes shell=/bin/bash home=/home/git
- name: Add git user authorized_key, in the case of a private repo you may want to use a deploy key, see https://developer.github.com/guides/managing-deploy-keys/#deploy-keys
  authorized_key: user=git key="{{git_user_key}}"
- name: Create git repo directory
  file: path=/home/git/{{git_repo_dir}}/{{git_repo}} owner=git group=git mode=0755 state=directory
- name: Initialize bare git repo
  command: git init --bare chdir=/home/git/{{git_repo_dir}}/{{git_repo}}
  sudo: yes
  sudo_user: git
- name: Copy post-receive hook
  template: src=post-receive dest=/home/git/{{git_repo_dir}}/{{git_repo}}/hooks/post-receive
  sudo: yes
  sudo_user: git
  args:
    owner: git
    group: git
    mode: 0755