---
- name: Install git
  action: apt pkg=git-core state=installed
- name: Create git repo directory
  file: path=/home/cloud-user/{{git_repo_dir}}/{{git_repo}} owner=cloud-user group=cloud-user mode=0755 state=directory

- name: Initialize bare git repo
  # become: no
  git: 
      repo=git@github.com:{{githubuser}}/{{git_repo}}
      dest={{git_repo_dir}}/{{git_repo}}
      accept_hostkey=yes
      force=yes
      bare=yes
      remote={{githubuser}}
      recursive=no
      update=yes
      key_file=/home/cloud-user/.ssh/id_rsa.pub
      version={{githubbranch}}

- name: Copy post-receive hook
  template: src=post-receive dest=/home/cloud-user/{{git_repo_dir}}/{{git_repo}}/hooks/post-receive
  become: yes
  become_user: cloud-user
  args:
    owner: cloud-user
    group: cloud-user
    mode: 0755
